import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/Navbar";
import StickyFooter from "@/components/StickyFooter";

const garet = localFont({
  src: [
    { path: "../public/font/Garet-Thin.ttf", weight: "100", style: "normal" },
    {
      path: "../public/font/GaretThinitalic.ttf",
      weight: "100",
      style: "italic",
    },
    { path: "../public/font/GaretLight.ttf", weight: "200", style: "normal" },
    {
      path: "../public/font/GaretLightItalic.ttf",
      weight: "200",
      style: "italic",
    },
    { path: "../public/font/Garet-Book.ttf", weight: "300", style: "normal" },
    {
      path: "../public/font/GaretBookItalic.ttf",
      weight: "300",
      style: "italic",
    },
    {
      path: "../public/font/Garet-Regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/font/GaretRegularItalic.ttf",
      weight: "400",
      style: "italic",
    },
    { path: "../public/font/GaretMedium.ttf", weight: "500", style: "normal" },
    {
      path: "../public/font/GaretMediumItalic.ttf",
      weight: "500",
      style: "italic",
    },
    { path: "../public/font/GaretBold.ttf", weight: "600", style: "normal" },
    {
      path: "../public/font/GaretBoldItalic.ttf",
      weight: "600",
      style: "italic",
    },
    {
      path: "../public/font/GaretExtraBold.ttf",
      weight: "700",
      style: "normal",
    },
    { path: "../public/font/Garet-Heavy.ttf", weight: "800", style: "normal" },
    {
      path: "../public/font/GaretHeavyItalic.ttf",
      weight: "800",
      style: "italic",
    },
    { path: "../public/font/GaretFat.ttf", weight: "900", style: "normal" },
  ],
  variable: "--font-garet",
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${garet.variable} font-garet bg-dnm-white`}>
        <div className="p-4">
          <Navbar />
          {children}
        </div>
        <StickyFooter />
      </body>
    </html>
  );
}
